version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore"
      prefix-development: "chore(dev)"
      include: "scope"
    labels:
      - "dependencies"
    groups:
      python-prod:
        dependency-type: "production"
      python-dev:
        dependency-type: "development"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
    open-pull-requests-limit: 3
